# Site settings
title: Coding with Aly
header-img: img/home-bg.png
email: clairaly13@gmail.com
copyright_name: clairaly
description: > # this means to ignore newlines until "baseurl:"
  If I can learn to code, then so can you!
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  clairaly
learn_profile: clairaly
email_username: clairaly13@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
